server:
  application:
    name: devices-system
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/devices_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: devices-system
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml
